export async function extractYouTubeTranscript(url: string): Promise<string | null> {
  const instances = [
    'https://pipedapi.kavin.rocks',
    'https://pipedapi.tokhmi.xyz',
    'https://pipedapi.smnz.de',
    'https://piped-api.garudalinux.org',
    'https://pipedapi.adminforge.de',
    'https://api.piped.projectsegfau.lt'
  ];

  let videoId = null;
  try {
    const parsedUrl = new URL(url);
    if (parsedUrl.hostname.includes('youtube.com')) {
      videoId = parsedUrl.searchParams.get('v');
    } else if (parsedUrl.hostname.includes('youtu.be')) {
      videoId = parsedUrl.pathname.slice(1);
    }
  } catch (e) {
    return null;
  }
  
  if (!videoId) {
    return null;
  }

  for (const instance of instances) {
    try {
      const response = await fetch(`${instance}/streams/${videoId}`);
      if (!response.ok) continue;

      const data = await response.json();
      const subtitles = data.subtitles;

      if (!subtitles || subtitles.length === 0) continue;

      let selectedSub = 
        subtitles.find((s: any) => s.code === 'bg') ||
        subtitles.find((s: any) => s.code === 'en' && !s.autoGenerated) ||
        subtitles.find((s: any) => s.code === 'en') ||
        subtitles[0];

      const subResponse = await fetch(selectedSub.url);
      if (!subResponse.ok) continue;

      const vttText = await subResponse.text();

      const cleanText = vttText
        .split('\n')
        .filter(line => 
          !line.includes('-->') && 
          !line.startsWith('WEBVTT') && 
          !line.startsWith('Kind:') && 
          !line.startsWith('Language:') &&
          line.trim() !== '' &&
          !/^\d+$/.test(line.trim())
        )
        .join(' ')
        .replace(/<[^>]+>/g, '')
        .replace(/&nbsp;/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();

      if (cleanText) return cleanText;
    } catch (error) {
      console.warn(`Failed to fetch from ${instance}`, error);
    }
  }
  
  return null;
}